export const authConstants = {
	REGISTER_SUCCESS: 'REGISTER_SUCCESS',
	REGISTER_FAIL: 'REGISTER_FAIL',
	USER_LOADING: 'USER_LOADING',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAIL: 'LOGIN_FAIL',
	AUTH_ERROR: 'AUTH_ERROR',
	LOGOUT_USER: 'LOGOUT_USER',
	SET_CURRENT_USER: 'SET_CURRENT_USER'
}
// export const geolocationConstants = {
// 	GET_GEOLOCATION = 'GET_GEOLOCATION',
// 	GEOLOCATION_DENIED = 'GEOLOCATION_DENIED'
// }

// export const weatherConstants = {
// 	GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER',
// 	GET_FORECAST = 'GET_FORECAST',
// 	SEARCH_WEATHER_LOCATION = 'SEARCH_WEATHER',
// 	UPDATE_METRIC = 'UPDATE_METRIC',
// 	UPDATE_IMPERIAL = 'UPDATE_IMPERIAL'
// }

export const todoConstants = {
	FETCH_TODOS: 'FETCH_TODOS',
	FETCH_TODOS_FAIL: 'FETCH_TODOS_FAIL',
	TODOS_LOADING: 'TODOS_LOADING',
	SINGLE_TODO_LOADING: 'SINGLE_TODO_LOADING',
	ADD_TODO: 'ADD_TODO',
	ADD_TODO_FAIL: 'ADD_TODO_FAIL',
	DELETE_TODO: 'DELETE_TODO',
	DELETE_TODO_FAIL: 'DELETE_TODO_FAIL',
	EDIT_TODO: 'EDIT_TODO',
	EDIT_TODO_FAIL: 'EDIT_TODO_FAIL',
	SET_CURRENT_TODO: 'SET_CURRENT_TODO',
	CLEAR_CURRENT_TODO: 'CLEAR_CURRENT_TODO',
	SET_CLICKED_TODO: 'SET_CLICKED_TODO',
	CLEAR_CLICKED_TODO: 'CLEAR_CLICKED_TODO',
	SET_TODO_COMPLETE: 'SET_TODO_COMPLETE',
	SET_TODO_COMPLETE_FAIL: 'SET_TODO_COMPLETE_FAIL',
	UNSET_TODO_COMPLETE: 'UNSET_TODO_COMPLETE',
	UNSET_TODO_COMPLETE_FAIL: 'UNSET_TODO_COMPLETE_FAIL'
}

// export const userConstants = {
// 	LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
// 	LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
// 	LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

// 	LOGOUT: 'USERS_LOGOUT',

// 	GETALL_REQUEST: 'USERS_GETALL_REQUEST',
// 	GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
// 	GETALL_FAILURE: 'USERS_GETALL_FAILURE'
// }