export const todoConstants = {
	FETCH_TODOS: 'FETCH_TODOS',
	TODOS_LOADING: 'TODOS_LOADING',
	ADD_TODO: 'ADD_TODO',
	DELETE_TODO: 'DELETE_TODO',
	SET_CURRENT_TODO: 'SET_CURRENT_TODO',
	CLEAR_CURRENT_TODO: 'CLEAR_CURRENT_TODO',
	EDIT_TODO: 'EDIT_TODO',
	TODO_ERROR: 'TODO_ERROR',
}